[package]
name = "rs-domain-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.1"
nom = "7"
whois-rust = "1.5.1"
